name: Ingress-nginx workflow

on:
  push:
    tags:
      - 'ingress-pipeline*'

permissions:
  id-token: write  # Это разрешение необходимо для запроса JWT
  contents: read   # Это разрешение требуется для использования actions/checkout

jobs:    
  ingress-nginx:
    name: "Deploy ingress-nginx"
    uses: ./.github/workflows/action.yml
    with:
        PLAYBOOK: "ingress-nginx.yml"
        ANSIBLE_CONFIG: ${{ vars.ANSIBLE_CONFIG }}
        AWS_REGION: ${{ vars.AWS_REGION }}
